"""Helpers to build deterministic synthetic SRF fixtures inline in tests.

Keeping fixtures generated by code rather than checked in as files is helpful
when tweaking the format: every field is visible and the relationship between
inputs and expected outputs is explicit.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

# A minimal valid v1.0 SRF with one POINTS block of 2 sources. The second one
# is intentionally empty (zero samples in all three directions); the parser
# must drop it.
SRF_V10_MINIMAL = dedent("""\
    1.0
    POINTS 2
    -118.5 34.3 5.0 90.0 60.0 1.0e8 0.5 0.01
    180.0 100.0 4 0.0 0 0.0 0
    0.0 1.0 2.0 0.0
    -118.6 34.4 6.0 90.0 60.0 1.0e8 0.5 0.01
    180.0 0.0 0 0.0 0 0.0 0
    """)

# A v2.0 SRF with one source that exercises:
#   * non-zero vs and den (so shear modulus is non-trivial)
#   * non-zero slip in two of three directions
#   * an explicit PLANE block (must be skipped)
#   * a comment line (must be ignored)
SRF_V20_TWO_DIR = dedent("""\
    2.0
    # comment line that should be ignored
    PLANE 1
    -118.5 34.3 4 4 8.0 8.0
    90.0 60.0 0.0 4.0 4.0
    POINTS 1
    -118.5 34.3 5.0 90.0 60.0 1.0e8 0.0 0.01 350000.0 2.7
    45.0 1.0 3 0.0 2 0.0 0
    1.0 2.0 1.5
    0.5 0.25
    """)

# v1.0 with a single source containing five samples in u1, used to validate
# slip path integration in the XDMF writer.
SRF_V10_FOR_SLIP_INTEGRATION = dedent("""\
    1.0
    POINTS 1
    0.0 0.0 1.0 0.0 90.0 1.0e4 0.0 0.5
    0.0 4.0 5 0.0 0 0.0 0
    1.0 2.0 3.0 2.0 1.0
    """)


def write_srf(text: str, dst: Path) -> Path:
    """Write ``text`` to ``dst`` and return ``dst`` for convenience."""
    dst.write_text(text)
    return dst
